### PR TITLE
Add build event

### PR DESCRIPTION
**Pull request by on99**

### CODE REVIEW

**Comment by it33** [comment]
Thanks on99, definitely appreciate the addition, 

When the Mattermost core team open sourced this integration, the goal was to seed the community with code that could be reused for a broad range of applications. 

We're wondering if someone else from the community were interested in becoming the recommended fork of this integration in future? 

@NotSqrt, I noticed [your fork has test cases built for Mattermost already](https://github.com/NotSqrt/mattermost-integration-gitlab), I wondered if you'd be open to taking PRs like one?

If so, we could redirect the link from http://www.mattermost.org/community-applications/ to your repo, and also recommend it from our README file?

**Comment by NotSqrt** [comment]
@it33 Yes, I'm ok with my fork becoming a recommended option.

I've set up tests after saving the various messages sent by gitlab in all the cases (including builds).
It's pip-installable from the git repository (not released on PyPI), and tested against multiple versions of python.

The last step is probably to provide easier configuration and customization (including the format of each message)

**Comment by it33** [comment]
Excellent! Thanks @NotSqrt!

I've replaced the link for mattermost-integration-gitlab with a link to your repo: http://www.mattermost.org/community-applications/

@on99, would you be open to moving your pull request to https://github.com/NotSqrt/mattermost-integration-gitlab?

**Comment by NotSqrt** [comment]
@on99 I've already plugged build events (my CIEvent class), but the formatting may not be what you want.
I don't use them for the moment, I hoped that the various builds of a commit could be grouped in a table, but it's not possible right now. So I don't remember if all is well and working.

**Comment by on99** [comment]
@NotSqrt  Thank you. Your fork is OK to me.

**Pull request closed without merging**
